# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jessicab/aestream

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jessicab/aestream

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jessicab/aestream/CMakeFiles /home/jessicab/aestream//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jessicab/aestream/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aedat4

# Build rule for target.
aedat4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aedat4
.PHONY : aedat4

# fast build rule for target.
aedat4/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/aedat4.dir/build.make src/CMakeFiles/aedat4.dir/build
.PHONY : aedat4/fast

#=============================================================================
# Target rules for targets named aestream_lib

# Build rule for target.
aestream_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aestream_lib
.PHONY : aestream_lib

# fast build rule for target.
aestream_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/aestream_lib.dir/build.make src/CMakeFiles/aestream_lib.dir/build
.PHONY : aestream_lib/fast

#=============================================================================
# Target rules for targets named aestream

# Build rule for target.
aestream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aestream
.PHONY : aestream

# fast build rule for target.
aestream/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/aestream.dir/build.make src/CMakeFiles/aestream.dir/build
.PHONY : aestream/fast

#=============================================================================
# Target rules for targets named flatbuffers

# Build rule for target.
flatbuffers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatbuffers
.PHONY : flatbuffers

# fast build rule for target.
flatbuffers/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flatbuffers.dir/build.make _deps/flatbuffers-build/CMakeFiles/flatbuffers.dir/build
.PHONY : flatbuffers/fast

#=============================================================================
# Target rules for targets named flatc

# Build rule for target.
flatc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatc
.PHONY : flatc

# fast build rule for target.
flatc/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flatc.dir/build.make _deps/flatbuffers-build/CMakeFiles/flatc.dir/build
.PHONY : flatc/fast

#=============================================================================
# Target rules for targets named flathash

# Build rule for target.
flathash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flathash
.PHONY : flathash

# fast build rule for target.
flathash/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flathash.dir/build.make _deps/flatbuffers-build/CMakeFiles/flathash.dir/build
.PHONY : flathash/fast

#=============================================================================
# Target rules for targets named flattests

# Build rule for target.
flattests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flattests
.PHONY : flattests

# fast build rule for target.
flattests/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flattests.dir/build.make _deps/flatbuffers-build/CMakeFiles/flattests.dir/build
.PHONY : flattests/fast

#=============================================================================
# Target rules for targets named flatsamplebinary

# Build rule for target.
flatsamplebinary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatsamplebinary
.PHONY : flatsamplebinary

# fast build rule for target.
flatsamplebinary/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flatsamplebinary.dir/build.make _deps/flatbuffers-build/CMakeFiles/flatsamplebinary.dir/build
.PHONY : flatsamplebinary/fast

#=============================================================================
# Target rules for targets named flatsampletext

# Build rule for target.
flatsampletext: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatsampletext
.PHONY : flatsampletext

# fast build rule for target.
flatsampletext/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flatsampletext.dir/build.make _deps/flatbuffers-build/CMakeFiles/flatsampletext.dir/build
.PHONY : flatsampletext/fast

#=============================================================================
# Target rules for targets named flatsamplebfbs

# Build rule for target.
flatsamplebfbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flatsamplebfbs
.PHONY : flatsamplebfbs

# fast build rule for target.
flatsamplebfbs/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/flatsamplebfbs.dir/build.make _deps/flatbuffers-build/CMakeFiles/flatsamplebfbs.dir/build
.PHONY : flatsamplebfbs/fast

#=============================================================================
# Target rules for targets named generated_code

# Build rule for target.
generated_code: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generated_code
.PHONY : generated_code

# fast build rule for target.
generated_code/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flatbuffers-build/CMakeFiles/generated_code.dir/build.make _deps/flatbuffers-build/CMakeFiles/generated_code.dir/build
.PHONY : generated_code/fast

#=============================================================================
# Target rules for targets named aestream_input

# Build rule for target.
aestream_input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aestream_input
.PHONY : aestream_input

# fast build rule for target.
aestream_input/fast:
	$(MAKE) $(MAKESILENT) -f src/input/CMakeFiles/aestream_input.dir/build.make src/input/CMakeFiles/aestream_input.dir/build
.PHONY : aestream_input/fast

#=============================================================================
# Target rules for targets named aestream_output

# Build rule for target.
aestream_output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aestream_output
.PHONY : aestream_output

# fast build rule for target.
aestream_output/fast:
	$(MAKE) $(MAKESILENT) -f src/output/CMakeFiles/aestream_output.dir/build.make src/output/CMakeFiles/aestream_output.dir/build
.PHONY : aestream_output/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... generated_code"
	@echo "... aedat4"
	@echo "... aestream"
	@echo "... aestream_input"
	@echo "... aestream_lib"
	@echo "... aestream_output"
	@echo "... flatbuffers"
	@echo "... flatc"
	@echo "... flathash"
	@echo "... flatsamplebfbs"
	@echo "... flatsamplebinary"
	@echo "... flatsampletext"
	@echo "... flattests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

