name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      # - uses: Jimver/cuda-toolkit@v0.2.8
      #   id: cuda-toolkit
      #   with:
      #     cuda: '11.7.0'
      - name: Install dependencies
        run: |
          pip install sphinx furo myst_parser sphinx-copybutton
      - name: Install aestream
        run: |
          pip install .
      - name: Sphinx build
        run: |
          sphinx-build -b html docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
